tilfin/ougai

- lib/ougai/formatters/readable.rb
- If `plain` of Readble is true, ASCII color sequence is disabled.
> Add plain, trace_indent to Readble formatter

- lib/ougai/logger.rb
> Add broadcast class method

- lib/ougai/formatters/base.rb
- lib/ougai/version.rb
- spec/formatters/base_spec.rb
> Fix to get hostname that contains UTF-8 chars

- README.md
- lib/ougai/logger.rb
- Add badges provided by codeclimate
- Fix an code issue in `debug`
> Fix code issues

- lib/ougai/logger.rb
- Shoten getting args
- Call add method directly
> Refactor to item

- lib/ougai/logger.rb
> Refactor to_item

- README.md
- lib/ougai/logger.rb
- lib/ougai/version.rb
- spec/logger_spec.rb
- Adding `logger.with_fields` to all logs for v1.0.0
> Implement with_fields

- README.md
- lib/ougai.rb
- lib/ougai/child_logger.rb
- lib/ougai/logger.rb
- lib/ougai/logging.rb
- lib/ougai/version.rb
- spec/child_logger_spec.rb
- spec/logging_spec.rb
> Support child logger

- README.md
- lib/ougai/child_logger.rb
- lib/ougai/logger.rb
- lib/ougai/logging.rb
- lib/ougai/version.rb
- spec/child_logger_spec.rb
- spec/logger_spec.rb
> Implement before_log attribute on logging

- lib/ougai/logging.rb
- for 1.4.0
- Up code climate evaluation
> Refactor logging

- README.md
- lib/ougai/logger.rb
- spec/logger_spec.rb
- for 1.4.0
- Implement level setter in broadcast
> Add broadcast test and explanation

- lib/ougai/logger.rb
- lib/ougai/version.rb
- spec/logger_spec.rb
> Add close method on broadcast building

- lib/ougai/formatters/bunyan.rb
- lib/ougai/version.rb
- spec/formatters/bunyan_spec.rb
> Bunyan supports with_newline attribute

- lib/ougai/child_logger.rb
- lib/ougai/formatters/bunyan.rb
- lib/ougai/formatters/readable.rb
- lib/ougai/logger.rb
- lib/ougai/logging.rb
- ougai.gemspec
> Add documents

- .travis.yml
- lib/ougai/child_logger.rb
- ougai.gemspec
- spec/child_logger_spec.rb
* Implement `ChildLogger#debug?|info?|warn?|error?|fatal?`
> Implement child logger's serverity? methods

- lib/ougai/logger.rb
- lib/ougai/version.rb
- spec/logger_spec.rb
> Fix broadcasting trace logs

- lib/ougai/formatters/base.rb
- lib/ougai/formatters/bunyan.rb
- lib/ougai/formatters/readable.rb
- lib/ougai/version.rb
- spec/formatters/base_spec.rb
- spec/formatters/bunyan_spec.rb
- spec/formatters/readable_spec.rb
The datetime format is fixed at ISO8601.
release for v1.5.2
> Support custom formatter uses datetime_format

- lib/ougai/formatters/readable.rb
- lib/ougai/version.rb
> Update Readable formatter extendable easily

- README.md
- lib/ougai/logging.rb
Pretty simple change. README updated, too.
> added block evaluation to Logging#child

- lib/ougai/child_logger.rb
- lib/ougai/logger.rb
- lib/ougai/logging.rb
- spec/logging_spec.rb
* reduce Hash.new
* reduce loop in merge
11.78sec -> 10.69sec  1M times
> Faster Hash merge

- lib/ougai/formatters/base.rb
- lib/ougai/formatters/readable.rb
- lib/ougai/version.rb
- spec/formatters/base_spec.rb
> Add serialize_backtrace attr to base formatter

- README.md
README.md has 2 examples which are mixed up.
> small fix in logging example in README.md

- lib/ougai/formatters/bunyan.rb
- lib/ougai/version.rb
- ougai.gemspec
> Use Oj in Bunyan formatter

- lib/ougai/version.rb
- ougai.gemspec
> Fix dependency on Oj

- Gemfile
- lib/ougai/formatters/bunyan.rb
- lib/ougai/formatters/for_json.rb
- lib/ougai/formatters/pino.rb
- lib/ougai/formatters/readable.rb
- spec/formatters/base_spec.rb
- spec/formatters/bunyan_spec.rb
- spec/formatters/pino_spec.rb
- spec/formatters/readable_spec.rb
- spec/spec_helper.rb
- Fix pino time that has epoch msec
- Add and refactor formatters spec
> Fix and refactor formatters

- lib/ougai/logger.rb
- lib/ougai/version.rb
- spec/logger_spec.rb
Fix no output if data is not a Hash or as Hash for v1.6.5
> Fix data not a Hash

- .travis.yml
- README.md
- lib/ougai/child_logger.rb
- lib/ougai/formatters/base.rb
- lib/ougai/formatters/bunyan.rb
- lib/ougai/formatters/for_json.rb
- lib/ougai/formatters/pino.rb
- lib/ougai/formatters/readable.rb
- lib/ougai/logger.rb
- lib/ougai/logging.rb
- lib/ougai/serializer.rb
- lib/ougai/serializers/json_jr_jackson.rb
- lib/ougai/serializers/json_oj.rb
- lib/ougai/version.rb
- ougai.gemspec
> Apply frozen_string_literal

- .rspec
- lib/ougai/child_logger.rb
- lib/ougai/logger.rb
- spec/formatters/readable_spec.rb
- spec/logger_spec.rb
> Fix warning on rspec

- .travis.yml
- ougai.gemspec
> Add Ruby 2.6 RC1 on Travis CI

- .travis.yml
- Update Ruby 2.6 to 2.6.1
- Add Ruby 2.7 Preview1
> Update ruby 2.6 and add ruby 2.7 PV1

- README.md
https://github.com/tilfin/ougai/issues/84#issuecomment-520534947
> Fix wrong example for broadcast

- lib/ougai/child_logger.rb
- lib/ougai/logger.rb
- lib/ougai/logging.rb
- spec/child_logger_spec.rb
- spec/logger_spec.rb
- spec/logging_spec.rb
- Split *Logging#child* into *Logger* and *ChildLogger*
- *Logger* has *child_class* specifying *ChildLogger*
> Generate sub-class ChildLogger for each sub-class Logger

- README.md
- lib/ougai/child_logger.rb
- lib/ougai/logging.rb
- spec/child_logger_spec.rb
> Implement level setter on child logger

- lib/ougai/logger.rb
- spec/logger_spec.rb
> Logger.new supports formatter argument

- .travis.yml
(Ruby 2.4.7 had some issues to install yesterday, so I left us at 2.4.6.)
> CI: Use ruby 2.3.8, 2.4.6, 2.5.6, 2.6.4

- lib/ougai/formatters/readable.rb
- lib/ougai/logger.rb
- lib/ougai/logging.rb
- spec/logger_spec.rb
Fixes #90 https://github.com/tilfin/ougai/issues/84#issuecomment-520684312
- Fix broadcast if a logging method is given a block
- Fix that the Readble formatter destroys data hash
> Fix broadcast

- .travis.yml
- Gemfile
- LICENSE.txt
- lib/ougai/version.rb
- ougai.gemspec
> Release v1.8.2

- README.md
- lib/ougai/version.rb
> Release v1.8.3

- Gemfile
- README.md
- lib/ougai/formatters/readable.rb
- ougai.gemspec
> Amazing print

- lib/ougai/logger.rb
- lib/ougai/logging.rb
- spec/logger_spec.rb
- spec/logging_spec.rb
Fixes #112
Logger and ChildLogger supports add method with Ougai extended arguments and log method that is the alias.
> Extended add and log methods of Logging

- .github/workflows/ci.yml
> Ruby 3.1 on CI
